# ARTIFICIAL NEURAL NETWORK


In [23]:
#importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

### DATA PREPROCESSING

In [24]:
#importing dataset and making it a vector for ANN

dataset = pd.read_csv('Churn_Modelling.csv')
print(dataset)
X = dataset.iloc[:, 3: -1].values
print(X)
Y = dataset.iloc[:, -1].values
print(Y)

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [25]:
#Encoding the categorical data (GENDER AND GEOGRAPHY)
#Label Encoding and One Hot encoding

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]
[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [26]:
#Split dataset into test and train

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [27]:
#Feature Scaling

from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train = scale.fit_transform(X_train)
X_test = scale.fit_transform(X_test)

### BUILDING ANN

In [28]:
# initializing the ANN
ann = tf.keras.models.Sequential()

#Adding input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#adding 2nd hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

#adding output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### TRAINIING THE MODEL

In [29]:
#Compiling the ANN
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics = ['accuracy'])

#training on the X_train
ann.fit(X_train, Y_train, batch_size = 32, epochs = 50)

Epoch 1/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7899 - accuracy: 0.5080
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.5206 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4710 - accuracy: 0.7972
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4332 - accuracy: 0.8135
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4032 - accuracy: 0.8313
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3844 - accuracy: 0.8394
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3740 - accuracy: 0.8432
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3680 - accuracy: 0.8445
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3635 - accuracy: 0.8459
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3603 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3313 - accuracy: 0.8633
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3314 - accuracy: 0.8626
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3312 - accuracy: 0.8646
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3315 - accuracy: 0.8648
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3311 - accuracy: 0.8648
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3309 - accuracy: 0.8661
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3313 - accuracy: 0.8643
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3307 - accuracy: 0.8648
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 0.8644
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3308 - accuracy: 

### MAKING PREDICTION AND EVALUATING THE MODEL

In [32]:
print(ann.predict(scale.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))


[[0.02422077]]


In [34]:
#predict the test set results and accuracy

Y_predi = ann.predict(X_test)
Y_predi1 = (Y_predi > 0.5)
print(np.concatenate((Y_predi.reshape(len(Y_predi),1), Y_predi1.reshape(len(Y_predi1),1), Y_test.reshape(len(Y_test),1)),1))

[[0.22958854 0.         0.        ]
 [0.27964336 0.         1.        ]
 [0.11574188 0.         0.        ]
 ...
 [0.13536328 0.         0.        ]
 [0.10998324 0.         0.        ]
 [0.17161381 0.         0.        ]]


In [36]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_predi1)
print(cm)
print(accuracy_score(Y_test, Y_predi1)*100)

[[1541   54]
 [ 218  187]]
86.4


In [39]:
# We can save the weights and biases in separate variables for easier examination
# Note that there can be hundreds or thousands of them!
weights = ann.layers[0].get_weights()[0]
weights

array([[ 2.9578668e-01, -6.5941401e-02,  1.1901066e-02, -9.7906613e-04,
         2.1319543e-01,  3.7896606e-01],
       [ 2.2669272e-01,  2.7374145e-01,  2.8657731e-01, -1.2313680e-01,
        -4.5869544e-02, -1.0596581e-01],
       [ 2.3360598e-01,  3.0686000e-01, -1.1309564e-02,  3.0161607e-01,
         2.9341972e-01,  9.9734187e-02],
       [ 6.4600721e-02,  2.6635057e-01, -6.0641263e-02,  2.1378877e-02,
        -1.8442890e-02, -8.0713026e-02],
       [ 5.3370722e-02, -4.3262014e-01,  7.8744330e-02,  1.5663457e-01,
         5.4025706e-02,  5.2633017e-01],
       [-1.0257326e+00, -8.3998866e-02, -1.4004998e-01,  8.6567384e-01,
        -1.0482458e-01, -4.0077239e-01],
       [ 3.3577412e-02,  7.4223822e-01, -9.9214368e-02,  4.7204703e-01,
        -3.2869413e-02, -3.2319179e-01],
       [-2.0783635e-02,  2.3358831e-01, -5.5968189e-01, -3.9846355e-01,
         2.8291836e-01, -2.8275809e-01],
       [-2.3912532e-02, -2.6029356e-02, -1.0739837e+00,  3.3195788e-01,
         1.3268484e+00, 

In [41]:
# We can save the weights and biases in separate variables for easier examination
# Note that there can be hundreds or thousands of them!
bias = ann.layers[0].get_weights()[1]
bias

array([ 1.3647165 , -0.14594811,  0.77224696, -0.12550503, -0.4190229 ,
       -0.19022508], dtype=float32)